# My Jupyter Notebook on IBM Watson Studio

**Shabareesh Aryan**  
Data Scientist

_`I love data science! I am interested in data science as the job profile really speaks to me. The skills required in this domain is relevant to my interests. I love building maching learning models and doing predictive analysis. I love math and I believe this is my dream job.`_

### The following code reverses a given list of numbers

In [11]:
def rev(n):
    return n[::-1]

In [10]:
for i in range(5):
    n = list(input().split(' '))
    print(rev(n))

1 2 3 4 5
['5', '4', '3', '2', '1']
44 55 66 77
['77', '66', '55', '44']
99 33 44 66 32
['32', '66', '44', '33', '99']
12 23 54 67 87
['87', '67', '54', '23', '12']
43 65 78
['78', '65', '43']

Tested lists | Results
--- | ---
1 2 3 4 5 | ['5', '4', '3', '2', '1']
44 55 66 77 | ['77', '66', '55', '44']
99 33 44 66 32 | ['32', '66', '44', '33', '99']
12 23 54 67 87 | ['87', '67', '54', '23', '12']
43 65 78 | ['78', '65', '43']